spring:
#  datasource:
#    h2
#    url: jdbc:h2:mem:testdb
#    driver-class-name: org.h2.Driver
#    username: sa
#    password:
  jpa:
    properties:
      hibernate:
        format_sql: true
        highlight_sql: true
        use_sql_comments: true
        default_batch_fetch_size: 500
logging:
  level:
    org:
      hibernate:
        SQL: debug
        orm:
          jdbc:
            bind: trace
      springframework:
        security: debug

auth:
  jwt:
    issuer: kotlin.moveuk.xyz
    secret: ThisIsRandomStringForJwtSecretKey
    accessTokenExpirationHour: 168